# Generated by Django 2.1.7 on 2019-03-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('illustration', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutting', models.TextField(null=True)),
                ('care_difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Moderate'), (3, 'Intermediate'), (4, 'Expert')])),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plenty_app.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blooming', models.TextField(null=True)),
                ('smell', models.IntegerField(choices=[(0, 'No smell'), (1, 'Subtle flowers smell'), (2, 'Intense flowers smell'), (3, 'Unpleasant flowers smell'), (4, 'Intense plant smell')])),
                ('light', models.IntegerField(choices=[(5, 'Very sunny'), (4, 'Sunny except noon'), (3, 'Usually sunny, tolerant, east side'), (2, 'Sunny except noon'), (1, 'Sunny but not direct, north side'), (0, 'In the shadows')])),
            ],
        ),
        migrations.CreateModel(
            name='PlantHumidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100, null=True)),
                ('season', models.IntegerField(choices=[(1, 'winter'), (2, 'spring'), (3, 'summer'), (4, 'autumn')], null=True)),
                ('watchout', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_C', models.IntegerField(null=True)),
                ('maximum_C', models.IntegerField(null=True)),
                ('season', models.IntegerField(choices=[(1, 'winter'), (2, 'spring'), (3, 'summer'), (4, 'autumn')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantWatering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence', models.IntegerField(null=True)),
                ('time_period', models.IntegerField(choices=[(1, 'weekly'), (2, 'monthly'), (3, 'quarterly')], null=True)),
                ('season', models.IntegerField(choices=[(1, 'winter'), (2, 'spring'), (3, 'summer'), (4, 'autumn')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Replanting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence', models.IntegerField(null=True)),
                ('time', models.IntegerField(choices=[(1, 'yearly'), (2, 'once every 2-3 years')], null=True)),
                ('season', models.IntegerField(choices=[(1, 'winter'), (2, 'spring'), (3, 'summer'), (4, 'autumn')], null=True)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'Novemer'), (12, 'December')], null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='plantdetails',
            name='humidity_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plenty_app.PlantHumidity'),
        ),
        migrations.AddField(
            model_name='plantdetails',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plenty_app.Plant'),
        ),
        migrations.AddField(
            model_name='plantdetails',
            name='temperature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plenty_app.PlantTemperature'),
        ),
        migrations.AddField(
            model_name='plantcare',
            name='replanting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plenty_app.Replanting'),
        ),
        migrations.AddField(
            model_name='plantcare',
            name='water',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plenty_app.PlantWatering'),
        ),
    ]
