# Generated by Django 2.1.7 on 2019-03-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenty_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantdetails',
            name='humidity_level',
        ),
        migrations.RemoveField(
            model_name='plantdetails',
            name='temperature',
        ),
        migrations.AddField(
            model_name='plantdetails',
            name='humidity',
            field=models.IntegerField(choices=[(0, 'low: no additional action'), (1, 'medium: spray once a week and/or flowerpot on wet stones'), (2, 'high: spray everyday and keep in flowerpot on wet stones')], null=True),
        ),
        migrations.AddField(
            model_name='plantdetails',
            name='maximum_C',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='plantdetails',
            name='minimum_C',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='PlantHumidity',
        ),
        migrations.DeleteModel(
            name='PlantTemperature',
        ),
    ]
