# Generated by Django 2.1.7 on 2019-04-03 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plenty_app', '0002_auto_20190328_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantcare',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='plantdetails',
            name='plant',
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_care',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plenty_app.PlantCare'),
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_det',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plenty_app.PlantDetails'),
        ),
    ]
